name: Daily Data Collection

on:
  schedule:
    # Run at 7:00 AM Vietnam time (UTC+7)
    - cron: '0 0 * * *'  # This is midnight UTC, which is 7 AM Vietnam time
  workflow_dispatch:  # Allows manual trigger

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client selenium webdriver_manager gspread_dataframe requests

    - name: Create credentials file
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
      
    - name: Run script
      env:
        USERNAME: ${{ secrets.QLONE_USERNAME }}
        PASSWORD: ${{ secrets.QLONE_PASSWORD }}
      run: |
        # Start Xvfb
        Xvfb :99 &
        export DISPLAY=:99
        
        # Run the script with increased debugging
        python -u main.py  # -u for unbuffered output
